export const API_ROUTE = "https://crowdsup-api.azurewebsites.net"
export const HOME_ROUTE = "/home"
export const REGISTER_ROUTE = "/register"
export const LOGIN_ROUTE = "/"
export const PERFIL_ROUTE = "/perfil"
